
version: '3.8'

volumes:
  oracle_data:

services:

  oracle:
    image: 'gvenzl/oracle-xe:18-slim'
    restart: always

    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=12
    volumes:
      - oracle_data:/u01/app/oracle
    ports:
      - "127.0.0.1:1525:1521"
      -   "5500:5500"

  app:
    restart: always
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:XE
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: 12
      JAVA_OPTS: '-Xmx512m'
  liquibase:
    image: 'liquibase/liquibase:latest'
    depends_on:
     - oracle
    entrypoint: [ "liquibase", "--changeLogFile=/liquibase/changelog/changelog.xml", "--url=jdbc:oracle:thin:@oracle:1521:XE", "--username=SYSTEM", "--password=12", "update" ]
    environment:
    - LIQUIBASE_URL=jdbc:oracle:thin:@oracle:1521:XE
    - LIQUIBASE_USERNAME=SYSTEM
    - LIQUIBASE_PASSWORD=12
    - LIQUIBASE_CHANGELOG=/liquibase/changelog/changelog.xml
    volumes:
      - C:\\Users\\hp\\Documents\\Solva_java\\SOLVA\\src\\main\\resources\\db\\changelog:/liquibase/changelog